# Generated by Django 2.2 on 2019-04-14 08:20

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('company_adress', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('site', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='prod_img', verbose_name='Фото продукции')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(choices=[(1, 'Купить вторичное сырье на переработку'), (2, 'Купить переработанное сырье'), (3, 'Продать вторичное сырье на переработку'), (4, 'Продать переработанное сырье')], default=0)),
                ('category1', models.IntegerField(blank=True, choices=[(1, 'ПП'), (2, 'ПНД'), (3, 'ПВД'), (4, 'Стрейч'), (5, 'ПЭТ'), (6, 'Другое')], default=0, null=True)),
                ('category2', models.IntegerField(blank=True, choices=[(1, 'Гранула ПП'), (2, 'Гранула ПНД'), (3, 'Гранула ПВД'), (4, 'Гранула стрейч'), (5, 'Другое')], default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
